services:
  api:
    build:
      dockerfile: qdrant_search/Dockerfile
    container_name: image-product-api
    volumes:
      - ./products:/app/products
    ports:
      - "8000:8000"
    depends_on:
      - qdrant  # если API зависит от Qdrant

  ui:
    build:
      dockerfile: ui/Dockerfile
    container_name: image-product-ui
    depends_on:
      - api
    volumes:
      - ./products:/app/products
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-local
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
