[project]
name = "image-product-search"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.10.0",
    "fastapi>=0.115.12",
    "numpy>=2.2.4",
    "pillow>=11.2.1",
    "torch>=2.6.0",
    "transformers>=4.51.2",
]
